language: php  # 我们代码所需要运行的环境平台

php:  # 需要测试的版本
- 5.6
- 7.0
- 7.1
- 7.2

# https://blog.csdn.net/u012348774/article/details/78663381?utm_source=blogxgwz1
dist: trusty   # 系统版本，
sudo: false  # 是否使用 sudo 模式

# 执行前需要运行的命令
# https://segmentfault.com/a/1190000005090444
# https://www.jianshu.com/p/673d82970d2d --no-interaction去掉交互信息
install: travis_retry composer install --no-interaction --prefer-source

# 主要构建命令
script: vendor/bin/phpunit --verbose